### ISSUE TITLE
Description for pl.wiki aliases is wrong

### ISSUE THREAD

**Issue by PiotrGackowski** [addshore/wikicrowd#48]
Description is correctly added to Polish aliases - but on wikicrowd have info that is English alias

<img width="678" alt="image" src="https://user-images.githubusercontent.com/2331033/161528516-1f2ef28a-b074-418d-99a4-5bfffc639ea7.png">

**Comment by waldyrious** [comment]
This was previously reported as #45, and was supposedly fixed in #46 :thinking:

**Comment by addshore** [comment]
https://github.com/addshore/wikicrowd/pull/46 altered the language used in the edit to Wikidata, but it looks like the UI text (which might be stored in each question) is still wrong!

**Comment by addshore** [comment]
Closing this, as I essentially think I'll sunset the aliases thing in its currnet form
